# typings/netCDF4.pyi

from typing import Any, Union

class Dataset:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def createDimension(self, dimname: str, size: Union[None, int]) -> None: ...
    def createVariable(self, varname: str, datatype: str, dimensions: tuple) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    variables: dict[str, Variable]
    dimensions: dict[str, Union[int, None]]

class Variable:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(
        self, key: Union[int, slice, tuple[Union[int, slice], ...]]
    ) -> Any: ...
    shape: tuple[int, ...]
    dimensions: tuple[str, ...]
